version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:\app
    environment:
      - DJANGO_SETTINGS_MODULE=circumatMasterProject.config.dev
      - DATASETS_VERSION=v4
      - DATASETS_DIR=data/
      - OPENBLAS_NUM_THREADS=3
    command: python manage.py runserver 